### DISCUSSION TITLE
Commands ignored in server console

### DISCUSSION THREAD

**Discussion by KasaiJo** [GameServerManagers/LinuxGSM#4694] [Q&A]
Hello,

I have set up two servers using the docker method (palworld, satisfactory). 
They work well but for both the commands I send in console mode are ignored.

Example for Palworld:
```yml
services:
  gsm_palworld:
    image: gameservermanagers/gameserver:pw
    container_name: gsm_palworld
    volumes:
      - ./data:/data
    ports:
      - "8211:8211/udp"
      - "27015:27015/udp"
      - "1985:1985/tcp"
    restart: unless-stopped
```

I paste the following parameter into the `common.cfg` file:
```ini
consoleinteract="yes"
```
Run server...
I connect to the console:
```sh
docker exec -it -u linuxgsm gsm_palworld ./pwserver console
```
Correct settings:
![image](https://github.com/user-attachments/assets/670df4a6-91b2-49d8-b1e0-10815e66e63e)

I'm trying out a few different commands (According to the palword doc it should be “/Save”, “/Info”):
![image](https://github.com/user-attachments/assets/38175912-2b89-473d-b065-b1ff857c8ec6)
but nothing happened...

I'm probably missing something, but why ?

-------
Setup:
Proxmox => VM Debian 12 => Docker container
Linux 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux
Docker version 27.3.1, build ce12230
