### ISSUE TITLE
[Bug]: Docker already has an entry in Crontab

### ISSUE THREAD

**Issue by ben-2357** [GameServerManagers/LinuxGSM#4745]
### User story

I want the crontab entry to be removed so users are able to set their own wihtout having to remove/comment it out every time the container is restarted.

### Game

PaperMC

### Linux distro

Ubuntu 22.04

### Command

command: update

### Further information

There is a cron entry in the container by default:
```bash
*/60 * * * * /app/pmcserver update > /dev/null 2>&1
```
I don't know if this is intentional, but it is very annoying because I'd like to set my own update interval without having to modify the actual application code. I didn't think it was necessary to make an issue for such a small problem. Thanks!

### Steps to reproduce

1. Use the container lol

**Comment by zuedev** [comment]
Which image are you using? I couldn't find any cron entries on the [latest GHCR build](https://github.com/gameservermanagers/docker-gameserver/pkgs/container/gameserver/334884938?tag=pmc).

**Comment by ben-2357** [comment]
Maybe it's because I'm using the Docker Hub image?:
```yaml
services:
  linuxgsm-pmc-bind:
    image: gameservermanagers/gameserver:pmc
    # image: ghcr.io/gameservermanagers/gameserver:pmc
```
Here's a [video ](https://streamable.com/yk75bo )showing the latest image.
